# Generated by Django 5.0.4 on 2024-04-13 02:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cargo',
            field=models.CharField(default='Sin asignar', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='departamento',
            field=models.CharField(default='Sin asignar', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employee',
            name='identificacion',
            field=models.CharField(default='Sin identificación', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='salario_mensual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='tipo_identificacion',
            field=models.CharField(choices=[('nit', 'NIT'), ('cc', 'Cédula de Ciudadanía')], default='nit', max_length=3),
        ),
    ]
