# Generated by Django 5.0.4 on 2024-04-13 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_cargo_employee_departamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cell', 'Celular'), ('tel', 'Teléfono')], max_length=4)),
                ('number', models.CharField(max_length=15)),
                ('area_code', models.CharField(blank=True, max_length=5, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='employee.employee')),
            ],
        ),
    ]
