# Generated by Django 5.0.4 on 2024-04-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_email_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[('cell', 'Celular'), ('tel', 'Teléfono')], default='cell', max_length=4),
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
