# Generated by Django 5.0.4 on 2024-04-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_phone_employee_employee_email_employee_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cargo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='departamento',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='identificacion',
            field=models.CharField(default='', max_length=20),
        ),
    ]
